package by.htp.ex.controller;

public enum CommandName {
	
	GO_TO_BASE_PAGE,
	GO_TO_LOGINATION_PAGE, 
	GO_TO_REGISTRATION_PAGE,
	GO_TO_NEWS_LIST, 
	GO_TO_VIEW_NEWS,
	GO_TO_ADD_NEWS,
	GO_TO_EDIT_NEWS,
	DO_SIGN_IN, 
	DO_SIGN_OUT,
	DO_REGISTRATION,		
	DO_EDIT_NEWS,
	ADD_NEWS,
	DELETE_NEWS,
	DO_LOCAL
}
